# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Characters

Character.create(name: 'Akira Yuki')
Character.create(name: 'Alpha-152')
Character.create(name: 'Ayane')
Character.create(name: 'Bass Armstrong/Mr. Strong')
Character.create(name: 'Bayman')
Character.create(name: 'Brad Wong')
Character.create(name: 'Christie')
Character.create(name: 'Ein')
Character.create(name: 'Eliot')
Character.create(name: 'Gen Fu')
Character.create(name: 'Hayate')
Character.create(name: 'Helena Douglas')
Character.create(name: 'Hitomi')
Character.create(name: 'Honoka')
Character.create(name: 'Jacky Bryant')
Character.create(name: 'Jann Lee')
@kasumi = Character.create(name: 'Kasumi')
Character.create(name: 'Kokoro')
Character.create(name: 'La Mariposa/Lisa Hamilton')
Character.create(name: 'Leifang')
Character.create(name: 'Leon')
Character.create(name: 'Mai Shiranui')
Character.create(name: 'Marie Rose')
Character.create(name: 'Mila')
Character.create(name: 'Momiji')
Character.create(name: 'Naotora Ii')
Character.create(name: 'Nyotengu')
Character.create(name: 'Pai Chan')
Character.create(name: 'Phase 4')
Character.create(name: 'Rachel')
Character.create(name: 'Raidou')
Character.create(name: 'Rig')
Character.create(name: 'Ryu Hayabusa')
Character.create(name: 'Sarah Bryant')
Character.create(name: 'Tina Armstrong')
Character.create(name: 'Zack')

# Costumes

# Kasumi
Costume.create(character: @kasumi, number: 1, name: 'Kasumi #01 - Costume 01')
Costume.create(character: @kasumi, number: 2, name: 'Kasumi #02 - Costume 02')
Costume.create(character: @kasumi, number: 3, name: 'Kasumi #03 - Costume 03')
Costume.create(character: @kasumi, number: 4, name: 'Kasumi #04 - Costume 04')
Costume.create(character: @kasumi, number: 5, name: 'Kasumi #05 - Costume 05')
Costume.create(character: @kasumi, number: 6, name: 'Kasumi #06 - Costume 06')
Costume.create(character: @kasumi, number: 7, name: 'Kasumi #07 - Costume 07')
Costume.create(character: @kasumi, number: 8, name: 'Kasumi #08 - Costume 08')
Costume.create(character: @kasumi, number: 9, name: 'Kasumi #09 - Costume 09')
Costume.create(character: @kasumi, number: 10, name: 'Kasumi #10 - Costume 10')
Costume.create(character: @kasumi, number: 11, name: 'Kasumi #11 - Costume 11')
Costume.create(character: @kasumi, number: 12, name: 'Kasumi #12 - Costume 12')
Costume.create(character: @kasumi, number: 13, name: 'Kasumi #13 - Costume 13')
Costume.create(character: @kasumi, number: 14, name: 'Kasumi #14 - Costume 14')
Costume.create(character: @kasumi, number: 15, name: 'Kasumi #15 - Costume 15')
Costume.create(character: @kasumi, number: 16, name: 'Kasumi #16 - Costume 16')
Costume.create(character: @kasumi, number: 17, name: 'Kasumi #17 - Costume 17')
Costume.create(character: @kasumi, number: 18, name: 'Kasumi #18 - Costume 18')
Costume.create(character: @kasumi, number: 19, name: 'Kasumi #19 - Costume 19')
Costume.create(character: @kasumi, number: 20, name: 'Kasumi #20 - Hot Getaway Pack 1')
Costume.create(character: @kasumi, number: 21, name: 'Kasumi #21 - Ultimate Sexy Costume')
Costume.create(character: @kasumi, number: 22, name: 'Kasumi #22 - Team D')
Costume.create(character: @kasumi, number: 23, name: 'Kasumi #23 - School Uniform')
Costume.create(character: @kasumi, number: 24, name: 'Kasumi #24 - Costume 24')
Costume.create(character: @kasumi, number: 25, name: 'Kasumi #25 - Costume 25')
Costume.create(character: @kasumi, number: 26, name: 'Kasumi #26 - Halloween Costume')
Costume.create(character: @kasumi, number: 27, name: 'Kasumi #27 - Costume 27')
Costume.create(character: @kasumi, number: 28, name: 'Kasumi #28 - Ragnarok Odyssey ACE Costume')
Costume.create(character: @kasumi, number: 29, name: 'Kasumi #29 - Tropical Sexy Costume Set')
Costume.create(character: @kasumi, number: 30, name: 'Kasumi #30 - Nurse Costumes')
Costume.create(character: @kasumi, number: 31, name: 'Kasumi #31 - Overalls')
Costume.create(character: @kasumi, number: 32, name: 'Kasumi #32 - Maid Costumes')
Costume.create(character: @kasumi, number: 33, name: 'Kasumi #33 - Ultimate Sexy Bunny')
Costume.create(character: @kasumi, number: 34, name: 'Kasumi #34 - Halloween Costume 2014')
Costume.create(character: @kasumi, number: 35, name: 'Kasumi #35 - Police Uniform')
Costume.create(character: @kasumi, number: 36, name: 'Kasumi #36 - Christmas')
Costume.create(character: @kasumi, number: 37, name: 'Kasumi #37 - Ninja 2015')
Costume.create(character: @kasumi, number: 38, name: 'Kasumi #38 - Last Getaway / Aloha')
Costume.create(character: @kasumi, number: 39, name: 'Kasumi #39 - Outcast Armor by Tamiki Wakaki Set')
Costume.create(character: @kasumi, number: 40, name: 'Kasumi #40 - Senran Kagura Mashup')
Costume.create(character: @kasumi, number: 41, name: 'Kasumi #41 - Fighter Force')
Costume.create(character: @kasumi, number: 42, name: 'Kasumi #42 - Deception')
Costume.create(character: @kasumi, number: 43, name: 'Kasumi #43 - Costumes by Tamiki Wakaki Set')
Costume.create(character: @kasumi, number: 44, name: 'Kasumi #44 - Hot Summer Costumes 2015')
Costume.create(character: @kasumi, number: 45, name: 'Kasumi #45 - Falcom Mashup Costumes')
Costume.create(character: @kasumi, number: 46, name: 'Kasumi #46 - Halloween 2015')
Costume.create(character: @kasumi, number: 47, name: 'Kasumi #47 - Schoolgirl Strikers Mashup')
Costume.create(character: @kasumi, number: 48, name: 'Kasumi #48 - "Designer\'s Choice 2015')
Costume.create(character: @kasumi, number: 49, name: 'Kasumi #49 - Season Pass 3')
Costume.create(character: @kasumi, number: 50, name: 'Kasumi #50 - Tatsunoko Mashup')
Costume.create(character: @kasumi, number: 51, name: 'Kasumi #51 - Valentine\'s Day')
Costume.create(character: @kasumi, number: 52, name: 'Kasumi #52 - Samurai Warriors')
Costume.create(character: @kasumi, number: 53, name: 'Kasumi #53 - GUST')
Costume.create(character: @kasumi, number: 54, name: 'Kasumi #54 - Fairy Tail')
Costume.create(character: @kasumi, number: 55, name: 'Kasumi #55 - DOA Festival 2016 Visitor\'s Award')
Costume.create(character: @kasumi, number: 56, name: 'Kasumi #56 - Attack on Titan')
Costume.create(character: @kasumi, number: 57, name: 'Kasumi #57 - Flower Set')
Costume.create(character: @kasumi, number: 58, name: 'Kasumi #58 - King of Fighters Collaboration')
Costume.create(character: @kasumi, number: 59, name: 'Kasumi #59 - Halloween 2016')
Costume.create(character: @kasumi, number: 60, name: 'Kasumi #60 - Summer Festival')
Costume.create(character: @kasumi, number: 61, name: 'Kasumi #61 - AQUAPLUS Collaboration')
Costume.create(character: @kasumi, number: 62, name: 'Kasumi #62 - High Society')
Costume.create(character: @kasumi, number: 63, name: 'Kasumi #63 - Chinese New Year')
Costume.create(character: @kasumi, number: 64, name: 'Kasumi #64 - Arc System Works Costume Set')
Costume.create(character: @kasumi, number: 65, name: 'Kasumi #65 - Shrine Maidens')
Costume.create(character: @kasumi, number: 66, name: 'Kasumi #66 - Rodeo Time Costumes')
Costume.create(character: @kasumi, number: 67, name: 'Kasumi #67 - Gust Mashup Swimwear')
