# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Character.create(name: 'Akira Yuki')
Character.create(name: 'Alpha-152')
Character.create(name: 'Ayane')
Character.create(name: 'Bass Armstrong/Mr. Strong')
Character.create(name: 'Bayman')
Character.create(name: 'Brad Wong')
Character.create(name: 'Christie')
Character.create(name: 'Ein')
Character.create(name: 'Eliot')
Character.create(name: 'Gen Fu')
Character.create(name: 'Hayate')
Character.create(name: 'Helena Douglas')
Character.create(name: 'Hitomi')
Character.create(name: 'Honoka')
Character.create(name: 'Jacky Bryant')
Character.create(name: 'Jann Lee')
Character.create(name: 'Kasumi')
Character.create(name: 'Kokoro')
Character.create(name: 'La Mariposa/Lisa Hamilton')
Character.create(name: 'Leifang')
Character.create(name: 'Leon')
Character.create(name: 'Mai Shiranui')
Character.create(name: 'Marie Rose')
Character.create(name: 'Mila')
Character.create(name: 'Momiji')
Character.create(name: 'Naotora Ii')
Character.create(name: 'Nyotengu')
Character.create(name: 'Pai Chan')
Character.create(name: 'Phase 4')
Character.create(name: 'Rachel')
Character.create(name: 'Raidou')
Character.create(name: 'Rig')
Character.create(name: 'Ryu Hayabusa')
Character.create(name: 'Sarah Bryant')
Character.create(name: 'Tina Armstrong')
Character.create(name: 'Zack')
