# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Characters

Character.create(name: 'Akira Yuki')
Character.create(name: 'Alpha-152')
Character.create(name: 'Ayane')
Character.create(name: 'Bass Armstrong/Mr. Strong')
Character.create(name: 'Bayman')
Character.create(name: 'Brad Wong')
Character.create(name: 'Christie')
Character.create(name: 'Ein')
Character.create(name: 'Eliot')
Character.create(name: 'Gen Fu')
Character.create(name: 'Hayate')
Character.create(name: 'Helena Douglas')
Character.create(name: 'Hitomi')
Character.create(name: 'Honoka')
Character.create(name: 'Jacky Bryant')
Character.create(name: 'Jann Lee')
@kasumi = Character.create(name: 'Kasumi')
Character.create(name: 'Kokoro')
Character.create(name: 'La Mariposa/Lisa Hamilton')
Character.create(name: 'Leifang')
Character.create(name: 'Leon')
Character.create(name: 'Mai Shiranui')
Character.create(name: 'Marie Rose')
Character.create(name: 'Mila')
Character.create(name: 'Momiji')
Character.create(name: 'Naotora Ii')
Character.create(name: 'Nyotengu')
Character.create(name: 'Pai Chan')
Character.create(name: 'Phase 4')
Character.create(name: 'Rachel')
Character.create(name: 'Raidou')
Character.create(name: 'Rig')
Character.create(name: 'Ryu Hayabusa')
Character.create(name: 'Sarah Bryant')
Character.create(name: 'Tina Armstrong')
Character.create(name: 'Zack')

# Costumes

# Kasumi
Costume.create(character: @kasumi, number: 1)
Costume.create(character: @kasumi, number: 2)
Costume.create(character: @kasumi, number: 3)
Costume.create(character: @kasumi, number: 4)
Costume.create(character: @kasumi, number: 5)
Costume.create(character: @kasumi, number: 6)
Costume.create(character: @kasumi, number: 7)
Costume.create(character: @kasumi, number: 8)
Costume.create(character: @kasumi, number: 9)
Costume.create(character: @kasumi, number: 10)
Costume.create(character: @kasumi, number: 11)
Costume.create(character: @kasumi, number: 12)
Costume.create(character: @kasumi, number: 13)
Costume.create(character: @kasumi, number: 14)
Costume.create(character: @kasumi, number: 15)
Costume.create(character: @kasumi, number: 16)
Costume.create(character: @kasumi, number: 17)
Costume.create(character: @kasumi, number: 18)
Costume.create(character: @kasumi, number: 19)
Costume.create(character: @kasumi, number: 20)
Costume.create(character: @kasumi, number: 21)
Costume.create(character: @kasumi, number: 22)
Costume.create(character: @kasumi, number: 23)
Costume.create(character: @kasumi, number: 24)
Costume.create(character: @kasumi, number: 25)
Costume.create(character: @kasumi, number: 26)
Costume.create(character: @kasumi, number: 27)
Costume.create(character: @kasumi, number: 28)
Costume.create(character: @kasumi, number: 29)
Costume.create(character: @kasumi, number: 30)
Costume.create(character: @kasumi, number: 31)
Costume.create(character: @kasumi, number: 32)
Costume.create(character: @kasumi, number: 33)
Costume.create(character: @kasumi, number: 34)
Costume.create(character: @kasumi, number: 35)
Costume.create(character: @kasumi, number: 36)
Costume.create(character: @kasumi, number: 37)
Costume.create(character: @kasumi, number: 38)
Costume.create(character: @kasumi, number: 39)
Costume.create(character: @kasumi, number: 40)
Costume.create(character: @kasumi, number: 41)
Costume.create(character: @kasumi, number: 42)
Costume.create(character: @kasumi, number: 43)
Costume.create(character: @kasumi, number: 44)
Costume.create(character: @kasumi, number: 45)
Costume.create(character: @kasumi, number: 46)
Costume.create(character: @kasumi, number: 47)
Costume.create(character: @kasumi, number: 48)
Costume.create(character: @kasumi, number: 49)
Costume.create(character: @kasumi, number: 50)
Costume.create(character: @kasumi, number: 51)
Costume.create(character: @kasumi, number: 52)
Costume.create(character: @kasumi, number: 53)
Costume.create(character: @kasumi, number: 54)
Costume.create(character: @kasumi, number: 55)
Costume.create(character: @kasumi, number: 56)
Costume.create(character: @kasumi, number: 57)
Costume.create(character: @kasumi, number: 58)
Costume.create(character: @kasumi, number: 59)
Costume.create(character: @kasumi, number: 60)
Costume.create(character: @kasumi, number: 61)
Costume.create(character: @kasumi, number: 62)
Costume.create(character: @kasumi, number: 63)
Costume.create(character: @kasumi, number: 64)
Costume.create(character: @kasumi, number: 65)
Costume.create(character: @kasumi, number: 66)
